# filepath: f:\my-portfolio.github.io\config.yaml
baseURL: "https://github.com/ToonLunk/my-portfolio.github.io"
languageCode: "en-us"
title: "Tyler Brock's Portfolio"
theme: "toha"
enableGitInfo: true
